import {
  AiOutlineBarChart,
  AiOutlineFileText,
  AiOutlineLogout,
  AiOutlineMail,
  AiOutlineSetting,
} from "react-icons/ai";
import {
  BsFillImageFill,
  BsPerson,
  BsReverseLayoutTextSidebarReverse,
} from "react-icons/bs";
export const Menu = [
  { title: "Dashboard", path: "/deshboard" },
  {
    title: "Pages",
    icon: <AiOutlineFileText />,
    path: "/",
    submenu: true,
    submenuItems: [
      { title: "Sign In", path: "/" },
      { title: "Sign Up", path: "/" },
      { title: "Reset Password", path: "/" },
      { title: "Invoice", path: "/" },
      { title: "Pricing", path: "/" },
      { title: "404 Page", path: "/" },
    ],
  },
  {
    title: "Documentation",
    submenuItems: [
      { title: "Introduction", path: "/" },
      { title: "Getting Started", path: "/" },
      { title: "Pluging", path: "/" },
    ],
    path: "/deshboard",
  },
  {
    title: "UI Elements",
    submenu: true,
    submenuItems: [
      { title: "Button", path: "/" },
      { title: "Cards", path: "/" },
      { title: "Carousel", path: "/" },
      { title: "Checkbox", path: "/" },
      { title: "Comment", path: "/" },
      { title: "Dropdowns", path: "/" },
      { title: "Feeds", path: "/" },
      { title: "Forms", path: "/" },
      { title: "Icon", path: "/" },
      { title: "Input Field", path: "/" },
      { title: "Loader", path: "/" },
      { title: "Modal", path: "/" },
      { title: "Pagination", path: "/" },
      { title: "Picker", path: "/" },
      { title: "Progress Bar", path: "/" },
      { title: "Radio Buttons", path: "/" },
      { title: "Search Field", path: "/" },
      { title: "Sidebar", path: "/" },
      { title: "Slider Controls", path: "/" },
      { title: "Tab Bar", path: "/" },
      { title: "Toggle", path: "/" },
    ],
    path: "/",
  },

  {
    title: "Media",
    spacing: true,
    icon: <BsFillImageFill />,
    path: "/",
  },
  {
    title: "Projects",
    icon: <BsReverseLayoutTextSidebarReverse />,
    path: "/",
    submenu: true,
    submenuItems: [
      { title: "submenu 1", path: "/" },
      { title: "submenu 2", path: "/" },
      { title: "submenu 3", path: "/" },
    ],
  },
  { title: "Analytics", icon: <AiOutlineBarChart />, path: "/" },
  { title: "Inbox", icon: <AiOutlineMail />, path: "/" },
  { title: "Profile", spacing: true, icon: <BsPerson />, path: "/" },
  { title: "Setting", icon: <AiOutlineSetting />, path: "/" },
  { title: "Logout", icon: <AiOutlineLogout />, path: "/" },
];
